name:                launchdarkly-server-sdk
version:             0.1.0
github:              "launchdarkly/haskell-server-sdk"
license:             Apache-2.0
license-file:        "LICENSE"
author:              "LaunchDarkly"
maintainer:          "dev@launchdarkly.com"
copyright:           "2019 Catamorphic, Co"

extra-source-files:
- README.md
- CHANGELOG.md
- LICENSE

synopsis:            Server-side SDK for integrating with LaunchDarkly
category:            Web

description:         Please see the README on GitHub at <https://github.com/launchdarkly/haskell-server-sdk#readme>

dependencies:
- base >= 4.7 && < 5
- text
- generic-lens
- lens
- aeson
- unordered-containers
- extra
- scientific
- iso8601-time
- time
- pcre-light
- bytestring
- semver
- vector
- cryptohash
- base16-bytestring
- bytestring-conversion
- hashtables
- http-client
- containers
- http-client-tls
- attoparsec
- mtl
- monad-logger
- exceptions
- http-types
- lrucache
- hedis
- retry

default-extensions:
- DeriveGeneric
- OverloadedStrings
- AllowAmbiguousTypes
- DataKinds
- DuplicateRecordFields
- FlexibleContexts
- NoMonomorphismRestriction
- TypeApplications
- DeriveAnyClass
- MultiParamTypeClasses
- LambdaCase
- RankNTypes
- FlexibleInstances
- GeneralizedNewtypeDeriving
- TemplateHaskell
- MultiWayIf
- TypeOperators
- DerivingStrategies
- ScopedTypeVariables
- MonoLocalBinds
- RecordWildCards

library:
  source-dirs: src
  ghc-options:
  - -fwarn-unused-imports
  - -Wall
  - -fno-warn-name-shadowing
  exposed-modules:
  - LaunchDarkly.Server
  - LaunchDarkly.Server.Config
  - LaunchDarkly.Server.User
  - LaunchDarkly.Server.Client

tests:
  haskell-server-sdk-test:
    main:                Spec.hs
    source-dirs:
    - test
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
