name:                launchdarkly-server-sdk
version:             0.2.0
github:              "launchdarkly/haskell-server-sdk"
license:             Apache-2.0
license-file:        "LICENSE"
author:              "LaunchDarkly"
maintainer:          "dev@launchdarkly.com"
copyright:           "2019 Catamorphic, Co"

extra-source-files:
- README.md
- CHANGELOG.md
- LICENSE

synopsis:            Server-side SDK for integrating with LaunchDarkly
category:            Web

description:         Please see the README on GitHub at <https://github.com/launchdarkly/haskell-server-sdk#readme>

dependencies:
- aeson
- attoparsec
- base >= 4.7 && < 5
- base16-bytestring
- bytestring
- bytestring-conversion
- containers
- cryptohash
- exceptions
- extra
- generic-lens
- hashtables
- hedis
- http-client
- http-client-tls
- http-types
- iso8601-time
- lens
- lrucache
- monad-logger
- mtl
- pcre-light
- retry
- scientific
- semver
- text
- time
- unordered-containers
- vector
- clock

default-extensions:
- AllowAmbiguousTypes
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MonoLocalBinds
- MultiParamTypeClasses
- MultiWayIf
- NoMonomorphismRestriction
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators

library:
  source-dirs: src
  ghc-options:
  - -fwarn-unused-imports
  - -Wall
  - -Wno-name-shadowing
  exposed-modules:
  - LaunchDarkly.Server
  - LaunchDarkly.Server.Client
  - LaunchDarkly.Server.Config
  - LaunchDarkly.Server.User
  - LaunchDarkly.Server.Store

tests:
  haskell-server-sdk-test:
    main:                Spec.hs
    source-dirs:
    - test
    - src
    - stores/launchdarkly-server-sdk-redis/src
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wno-name-shadowing
    dependencies:
    - HUnit
