name:                launchdarkly-server-sdk
version:             4.1.0 # x-release-please-version
github:              "launchdarkly/haskell-server-sdk"
license:             Apache-2.0
license-file:        "LICENSE"
author:              "LaunchDarkly"
maintainer:          "dev@launchdarkly.com"
copyright:           "2019 Catamorphic, Co"

extra-source-files:
- README.md
- CHANGELOG.md
- LICENSE
- test-data/**/*.json

synopsis:            Server-side SDK for integrating with LaunchDarkly
category:            Web

description:         Please see the README on GitHub at <https://github.com/launchdarkly/haskell-server-sdk#readme>

dependencies:
- aeson >=1.4.7.1 && <1.6 || >= 2.0.1.0 && <2.3
- attoparsec >=0.13.2.4 && <0.15
- base >=4.13 && <5
- base16-bytestring >=0.1.1.7 && <1.1
- bytestring >=0.10.10.1 && <0.12
- clock ==0.8.*
- containers >=0.6.2.1 && <0.7
- cryptohash >=0.11.9 && <0.12
- exceptions >=0.10.4 && <0.11
- extra >=1.7.9 && <1.8
- generic-lens >=2.0.0.0 && <2.3
- hashtables >=1.2.4.1 && <1.4
- http-client >=0.6.4.1 && <0.8
- http-client-tls >=0.3.5.3 && <0.4
- http-types >=0.12.3 && <0.13
- iso8601-time >=0.1.5 && <0.2
- lens >=4.18.1 && <5.3
- lrucache >=1.2.0.1 && <1.3
- memory>=0.15.0
- monad-logger >=0.3.36 && <0.4
- monad-loops ==0.4.*
- mtl >=2.2.2 && <2.4
- pcre-light >=0.4.1.0 && <0.5
- random >=1.1 && <1.3
- scientific >=0.3.6.2 && <0.4
- semver >=0.3.4 && <0.5
- text >=1.2.4.0 && <2.1
- time >=1.9.3 && <1.13
- unordered-containers >=0.2.10.0 && <0.3
- uuid >=1.3.13 && <1.4
- yaml >=0.11.5.0 && <0.12

default-extensions:
- AllowAmbiguousTypes
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MonoLocalBinds
- MultiParamTypeClasses
- MultiWayIf
- NoMonomorphismRestriction
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators

library:
  source-dirs: src
  ghc-options:
  - -fwarn-unused-imports
  - -Wall
  - -Wno-name-shadowing
  exposed-modules:
  - LaunchDarkly.AesonCompat
  - LaunchDarkly.Server
  - LaunchDarkly.Server.Client
  - LaunchDarkly.Server.Config
  - LaunchDarkly.Server.Context
  - LaunchDarkly.Server.Reference
  - LaunchDarkly.Server.Store
  - LaunchDarkly.Server.Integrations.FileData
  - LaunchDarkly.Server.Integrations.TestData

tests:
  haskell-server-sdk-test:
    main:                Spec.hs
    source-dirs:
    - test
    - src
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wno-name-shadowing
    - -fwarn-unused-imports
    dependencies:
    - HUnit
