name:                contract-tests
version:             0.0.1
github:              "launchdarkly/haskell-server-sdk"
license:             Apache-2.0
license-file:        "../LICENSE"
author:              "LaunchDarkly"
maintainer:          "dev@launchdarkly.com"
copyright:           "2019 Catamorphic, Co"

dependencies:
- aeson >=1.4.7.1 && <1.6 || >= 2.0.1.0 && <2.2
- base >=4.13 && <5
- containers >=0.6.2.1 && <0.7
- generic-lens >=2.0.0.0 && <2.3
- http-types >=0.12.3 && <0.13
- launchdarkly-server-sdk
- lens >=4.18.1 && <5.3
- mtl >=2.2.2 && <2.4
- scientific >=0.3.6.2 && <0.4
- scotty <1.0
- text >=1.2.4.0 && <2.1
- unordered-containers >=0.2.10.0 && <0.3

default-extensions:
- AllowAmbiguousTypes
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MonoLocalBinds
- MultiParamTypeClasses
- MultiWayIf
- NoMonomorphismRestriction
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators

executables:
  contract-tests:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
