name: CI Workflow
description: 'Shared CI workflow.'
inputs:
  resolver:
    description: 'Which resolver to use when building the package'
    required: false
    default: lts-18.28
  ghc-version:
    description: 'Which ghc version to use when building the package'
    required: false
    default: 8.10.7
  token:
    description: 'GH token used to download SDK test harness.'
    required: true
outputs:
  package-hashes:
    description: "base64-encoded sha256 hashes of distribution files"
    value: ${{ steps.package-hashes.outputs.package-hashes }}

runs:
  using: composite
  steps:
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ inputs.ghc-version }}
        enable-stack: true

    - name: Build library
      shell: bash
      run: stack --no-terminal --resolver=${{ inputs.resolver }} build

    - name: Build sdist distribution
      shell: bash
      run: stack --no-terminal --resolver=${{ inputs.resolver }} sdist

    - name: Setup dist directory
      shell: bash
      run: echo "STACK_DIR=$(stack --no-terminal path --dist-dir --resolver=${{ inputs.resolver }})" >> $GITHUB_ENV

    - name: Hash build files for provenance
      id: package-hashes
      shell: bash
      working-directory: ${{ env.STACK_DIR }}
      run: |
        echo "package-hashes=$(sha256sum *tar.gz | base64 -w0)" >> "$GITHUB_OUTPUT"

    - name: Run tests
      shell: bash
      run: stack --no-terminal --resolver=${{ inputs.resolver }} test

    - name: Build contract tests
      shell: bash
      run: STACKOPTS='--no-terminal --resolver=${{ inputs.resolver }}' make build-contract-tests

    - name: Start contract test service
      shell: bash
      run: STACKOPTS='--no-terminal --resolver=${{ inputs.resolver }}' make start-contract-test-service-bg

    - uses: launchdarkly/gh-actions/actions/contract-tests@contract-tests-v1.0.2
      with:
        test_service_port: 8000
        token: ${{ inputs.token }}
        extra_params: "-skip-from contract-tests/testharness-suppressions.txt"
