name: CI Workflow
description: 'Shared CI workflow.'
inputs:
  resolver:
    description: 'Which resolver to use when building the package'
    required: false
    default: lts-18.28
  ghc-version:
    description: 'Which ghc version to use when building the package'
    required: false
    default: 8.10.7
  token:
    description: 'GH token used to download SDK test harness.'
    required: true
outputs:
  dist-dir:
    description: "Path to the stack dist directory containing built artifacts"
    value: ${{ steps.dist-dir.outputs.dist-dir }}

runs:
  using: composite
  steps:
    - uses: haskell-actions/setup@f9150cb1d140e9a9271700670baa38991e6fa25c # v2
      with:
        ghc-version: ${{ inputs.ghc-version }}
        enable-stack: true

    - name: Build library
      shell: bash
      run: stack --no-terminal --resolver=${{ inputs.resolver }} build

    - name: Build sdist distribution
      shell: bash
      run: stack --no-terminal --resolver=${{ inputs.resolver }} sdist

    - name: Setup dist directory
      id: dist-dir
      shell: bash
      run: |
        STACK_DIR=$(stack --no-terminal path --dist-dir --resolver=${{ inputs.resolver }})
        echo "STACK_DIR=$STACK_DIR" >> $GITHUB_ENV
        echo "dist-dir=$STACK_DIR" >> "$GITHUB_OUTPUT"

    - name: Run tests
      shell: bash
      run: stack --no-terminal --resolver=${{ inputs.resolver }} test

    - name: Build contract tests
      shell: bash
      run: STACKOPTS='--no-terminal --resolver=${{ inputs.resolver }}' make build-contract-tests

    - name: Start contract test service
      shell: bash
      run: STACKOPTS='--no-terminal --resolver=${{ inputs.resolver }}' make start-contract-test-service-bg

    - uses: launchdarkly/gh-actions/actions/contract-tests@contract-tests-v1.0.2
      with:
        test_service_port: 8000
        token: ${{ inputs.token }}
        extra_params: "-skip-from contract-tests/testharness-suppressions.txt"
